version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.9
    working_directory: /home/circleci/go/src/github.com/RestGW/api-routerd
    environment:
      GOPATH: /home/circleci/go
    steps:
      - run:
          command:
            echo -e 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
            source /home/circleci/.bashrc
      - checkout
      - run:
          command: dep ensure
      - run:
          command: go build -v

workflows:
  version: 2
  test:
    jobs:
      - test
